"""initial schema

Revision ID: d0f5312f8c07
Revises: 
Create Date: 2026-08-07 17:55:43.504111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f5312f8c07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('api_documentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_source', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_documentations_id'), 'api_documentations', ['id'], unique=False)
    op.create_index(op.f('ix_api_documentations_user_id'), 'api_documentations', ['user_id'], unique=False)
    op.create_table('bug_debug_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_source', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_debug_sessions_id'), 'bug_debug_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_bug_debug_sessions_user_id'), 'bug_debug_sessions', ['user_id'], unique=False)
    op.create_table('code_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_explanations_id'), 'code_explanations', ['id'], unique=False)
    op.create_index(op.f('ix_code_explanations_user_id'), 'code_explanations', ['user_id'], unique=False)
    op.create_table('code_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_source', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_reviews_id'), 'code_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_code_reviews_user_id'), 'code_reviews', ['user_id'], unique=False)
    op.create_table('project_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idea', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_generations_id'), 'project_generations', ['id'], unique=False)
    op.create_index(op.f('ix_project_generations_user_id'), 'project_generations', ['user_id'], unique=False)
    op.create_table('readme_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_summary', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readme_generations_id'), 'readme_generations', ['id'], unique=False)
    op.create_index(op.f('ix_readme_generations_user_id'), 'readme_generations', ['user_id'], unique=False)
    op.create_table('repository_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_source', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_analyses_id'), 'repository_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_repository_analyses_user_id'), 'repository_analyses', ['user_id'], unique=False)
    op.create_table('repository_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('cited_files', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['repository_analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_chat_messages_analysis_id'), 'repository_chat_messages', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_repository_chat_messages_id'), 'repository_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_repository_chat_messages_user_id'), 'repository_chat_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_chat_messages_user_id'), table_name='repository_chat_messages')
    op.drop_index(op.f('ix_repository_chat_messages_id'), table_name='repository_chat_messages')
    op.drop_index(op.f('ix_repository_chat_messages_analysis_id'), table_name='repository_chat_messages')
    op.drop_table('repository_chat_messages')
    op.drop_index(op.f('ix_repository_analyses_user_id'), table_name='repository_analyses')
    op.drop_index(op.f('ix_repository_analyses_id'), table_name='repository_analyses')
    op.drop_table('repository_analyses')
    op.drop_index(op.f('ix_readme_generations_user_id'), table_name='readme_generations')
    op.drop_index(op.f('ix_readme_generations_id'), table_name='readme_generations')
    op.drop_table('readme_generations')
    op.drop_index(op.f('ix_project_generations_user_id'), table_name='project_generations')
    op.drop_index(op.f('ix_project_generations_id'), table_name='project_generations')
    op.drop_table('project_generations')
    op.drop_index(op.f('ix_code_reviews_user_id'), table_name='code_reviews')
    op.drop_index(op.f('ix_code_reviews_id'), table_name='code_reviews')
    op.drop_table('code_reviews')
    op.drop_index(op.f('ix_code_explanations_user_id'), table_name='code_explanations')
    op.drop_index(op.f('ix_code_explanations_id'), table_name='code_explanations')
    op.drop_table('code_explanations')
    op.drop_index(op.f('ix_bug_debug_sessions_user_id'), table_name='bug_debug_sessions')
    op.drop_index(op.f('ix_bug_debug_sessions_id'), table_name='bug_debug_sessions')
    op.drop_table('bug_debug_sessions')
    op.drop_index(op.f('ix_api_documentations_user_id'), table_name='api_documentations')
    op.drop_index(op.f('ix_api_documentations_id'), table_name='api_documentations')
    op.drop_table('api_documentations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
